"""initial_schema

Revision ID: 6539a82b1bbe
Revises: 
Create Date: 2026-07-12 09:54:07.315109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6539a82b1bbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('party_type', sa.Enum('customer', 'shoper', name='module_type'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('mobile2', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parties_name', 'parties', ['name'], unique=False)
    op.create_index(op.f('ix_parties_party_type'), 'parties', ['party_type'], unique=False)
    op.create_index('ix_parties_type_name', 'parties', ['party_type', 'name'], unique=False)
    op.create_table('products',
    sa.Column('party_type', sa.Enum('customer', 'shoper', name='module_type'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_unit', sa.String(length=40), nullable=True),
    sa.Column('default_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_party_type'), 'products', ['party_type'], unique=False)
    op.create_index('ix_products_type_name', 'products', ['party_type', 'name'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'owner', 'staff', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('party_type', sa.Enum('customer', 'shoper', name='module_type'), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_party_id'), 'invoices', ['party_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('item_type', sa.Enum('inventory', 'service', name='invoice_item_type'), nullable=False),
    sa.Column('is_manual_total', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('purchase_returns',
    sa.Column('return_number', sa.String(length=60), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reference_invoice_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_returns_party_id'), 'purchase_returns', ['party_id'], unique=False)
    op.create_index(op.f('ix_purchase_returns_reference_invoice_id'), 'purchase_returns', ['reference_invoice_id'], unique=False)
    op.create_index(op.f('ix_purchase_returns_return_date'), 'purchase_returns', ['return_date'], unique=False)
    op.create_index(op.f('ix_purchase_returns_return_number'), 'purchase_returns', ['return_number'], unique=True)
    op.create_table('ledger_entries',
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.Enum('sale', 'payment', 'debit', 'credit', 'opening', 'advance_received', 'advance_paid', 'adjustment', 'return', name='entry_type'), nullable=False),
    sa.Column('particulars', sa.String(length=500), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('running_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('cash', 'upi', 'bank_transfer', 'cheque', 'other', name='payment_mode'), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('purchase_return_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchase_returns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_entry_date'), 'ledger_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_ledger_entries_party_id'), 'ledger_entries', ['party_id'], unique=False)
    op.create_index('ix_ledger_party_date', 'ledger_entries', ['party_id', 'entry_date'], unique=False)
    op.create_table('purchase_return_items',
    sa.Column('purchase_return_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('is_manual_total', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchase_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_return_items_purchase_return_id'), 'purchase_return_items', ['purchase_return_id'], unique=False)
    op.create_table('invoice_adjustments',
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('payment_ledger_entry_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('adjustment_ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adjustment_ledger_entry_id'], ['ledger_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_ledger_entry_id'], ['ledger_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_adjustments_party_id'), 'invoice_adjustments', ['party_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('payment_type', sa.Enum('RECEIVED', 'GIVEN', name='payment_transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('cash', 'upi', 'bank_transfer', 'cheque', 'other', name='payment_mode'), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_customer_id'), 'payment_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_transaction_date'), 'payment_transactions', ['transaction_date'], unique=False)
    op.create_index('ix_payment_txn_customer_date', 'payment_transactions', ['customer_id', 'transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_txn_customer_date', table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_transaction_date'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_customer_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_invoice_adjustments_party_id'), table_name='invoice_adjustments')
    op.drop_table('invoice_adjustments')
    op.drop_index(op.f('ix_purchase_return_items_purchase_return_id'), table_name='purchase_return_items')
    op.drop_table('purchase_return_items')
    op.drop_index('ix_ledger_party_date', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_party_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_entry_date'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_purchase_returns_return_number'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_return_date'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_reference_invoice_id'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_party_id'), table_name='purchase_returns')
    op.drop_table('purchase_returns')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_party_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index('ix_products_type_name', table_name='products')
    op.drop_index(op.f('ix_products_party_type'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_parties_type_name', table_name='parties')
    op.drop_index(op.f('ix_parties_party_type'), table_name='parties')
    op.drop_index('ix_parties_name', table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
